# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=35)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('foneResidencial', models.CharField(max_length=15)),
                ('foneTrabalho', models.CharField(max_length=15)),
                ('rendaFamiliar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=35)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('fone', models.CharField(max_length=15)),
                ('responsavel', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('dataPedido', models.DateField()),
                ('dataRecebimento', models.DateField()),
                ('precoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigoFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProduto', models.IntegerField()),
                ('nomeProduto', models.CharField(max_length=35)),
                ('quantidade', models.IntegerField()),
                ('minQuantidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codigoVenda', models.AutoField(primary_key=True, serialize=False)),
                ('dataVenda', models.DateField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='codigoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='codigoVenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Venda'),
        ),
    ]
